title: HexOps
email: optional: your-email@example.com
description: >- # This site is the official coming soon page for the HexOps project.
The official coming soon page for the HexOps project.
Stay updated on the latest development news.

baseurl: "https://psocik.github.io/ho.github.io/"